// 全部界面文案集中于此（i18n 扩展位：后续按 locale 拆分本文件即可）
export const S = {
  appName: "Books Converter",
  nav: {
    convert: "转换",
    library: "产物库",
    manual: "手册",
    settings: "设置",
    notifications: "通知",
    collapse: "收起导航栏",
    expand: "展开导航栏",
  },
  notify: {
    title: "通知",
    clear: "清空",
    markRead: "全部已读",
    deleteOne: "删除此条",
  },
  convert: {
    title: "转换",
    dropTitle: "拖入 PDF 加入队列",
    dropHint: "支持多本排队；仅接受 .pdf 文件",
    dropBrowse: "点击选择文件",
    dropActive: "松开以加入队列",
    notPdf: "已跳过非 PDF 文件",
    optionsTitle: "转换选项",
    modeRule: "规则",
    modeRuleDesc: "云端 OCR 解析 + 后处理模型重建结构，成本近零",
    modeVlm: "VLM",
    modeVlmDesc: "多模态大模型逐页直读，结构理解最好",
    parseModel: "解析模型",
    parseModelMineru: "MinerU",
    parseModelMineruDesc: "高精度，适合复杂排版",
    parseModelPaddleocr: "PaddleOCR-VL",
    parseModelPaddleocrDesc: "免费额度 3000 页/天",
    tokenMissing: "未配置 Token",
    goSettings: "去设置",
    ocrLabel: "强制 OCR",
    ocrDesc: "扫描件与公式密集书籍必须开启（文字层直取时公式质量严重下降）；仅纯文字版 PDF 可关闭提速",
    postModel: "后处理模型",
    postModelDesc: "重建章节结构的文本模型",
    vlmModel: "多模态模型",
    vlmModelHint:
      "模型能力直接决定转换质量。请选用 DeepSeek-V4.1-Flash、GLM-5.3-Flash 或更先进的型号——旧型号格式服从性不足（GLM-4.6V 实测翻车），不要贪便宜。",
    reasoningNa: "该模型的思考模式由服务端决定，无需选择",
    newBadge: "NEW",
    vlmModelEmpty: "暂无可用视觉模型",
    goActivate: "去设置激活",
    translateLabel: "翻译",
    translateDesc: "转换后调用后处理模型翻译全书",
    translateLang: "目标语言",
    outputDir: "输出目录",
    outputDirPick: "选择目录",
    outputDirEmpty: "未设置（开始时用默认目录）",
    formatLabel: "导出格式",
    mdSplit: "Markdown 分章",
    mdSplitDesc: "按章拆分为 index.md + chapters/",
    mdDialect: "Markdown 方言",
    texFull: "完整 TeX 文档",
    texFullDesc: "关闭则只产片段（可直接 \\input）",
    exportLang: "导出语言",
    exportLangAuto: "自动（有译文用译文）",
    exportLangOrig: "仅原文",
    exportLangTrans: "仅译文",
    exportLangBoth: "原文+译文双出",
    reasoning: "思考档",
    workers: "并发 workers",
    queueTitle: "转换队列",
    startAll: "开始转换",
    clearFinished: "清除已完成",
    cancel: "取消",
    cancelTooltip: "取消该任务",
    expandLog: "展开日志",
    collapseLog: "收起日志",
    statusQueued: "待开始",
    statusRunning: "进行中",
    statusDone: "完成",
    statusError: "失败",
    statusCancelled: "已取消",
    stalled: "已停滞，建议取消并检查配置（如密钥、网络）",
    openEpub: "打开 EPUB",
    techDetail: "技术细节",
    noLogs: "（暂无日志）",
    stageProgress: (stage: number, total: number, name: string) => `阶段 ${stage}/${total} · ${name}`,
    logStart: (title: string, engine: string) => `开始转换《${title}》（引擎 ${engine}）`,
    logStageDone: (stage: number, name: string, elapsed: number) =>
      `✓ 阶段 ${stage}（${name}）完成，${elapsed}s`,
    exitCode: (code: number | null) => `进程退出码 ${code ?? "未知"}`,
    toastEnqueued: (n: number) => `已加入队列：${n} 本（点「开始转换」开跑）`,
    toastDone: (title: string) => `转换完成：《${title}》`,
    toastError: (title: string) => `转换失败：《${title}》`,
    toastCancelled: "已取消",
    toastDefaultDir: (dir: string) => `未设置输出目录，已使用默认：${dir}`,
    toastMissingKey: (what: string) => `缺少 ${what}，请到设置页配置`,
    toastCancelStuck: "取消请求未响应，进程可能僵死",
    needFormat: "至少选择一种导出格式",
  },
  library: {
    title: "产物库",
    search: "按书名搜索…",
    filterFormat: "全部格式",
    filterEngine: "全部引擎",
    refresh: "刷新",
    refreshTooltip: "重新读取登记处并校验文件",
    addScanDir: "添加扫描目录",
    addScanDirTooltip: "把旧产物目录加入扫描范围",
    scanDirs: "扫描目录",
    badgeMissing: "丢失",
    badgeUnregistered: "未登记",
    back: "返回产物库",
    detailTitle: "产物详情",
    metaTitle: "元数据",
    metaSource: "源 PDF",
    metaWorkDir: "工作目录",
    metaEngine: "解析引擎",
    metaOcr: "强制 OCR",
    metaTranslate: "翻译",
    metaElapsed: "耗时",
    metaVersion: "应用版本",
    metaTime: "完成时间",
    metaFormats: "导出格式",
    filesTitle: "产物清单",
    open: "打开",
    reveal: "在文件夹显示",
    relocate: "重新定位",
    relocateTooltip: "文件被移动后重新指定路径",
    remove: "从列表移除",
    removeConfirm: "确认移除？",
    removeTooltip: "从登记处删除该条（不删除文件）",
    toastRelocated: "已重新定位",
    toastRemoved: "已从列表移除",
    toastRefreshed: "产物库已刷新",
    reconvert: "再次转换",
    reconvertTooltip: "按原选项重新转换",
    sourceMissing: (path: string) => `源 PDF 已不在原位置：${path}`,
    toastReconvert: "已按原选项加入队列，点击开始转换",
    toastModelFallback: (m: string) => `原模型 ${m} 已不在激活列表，已回退当前默认`,
    noTitle: "（无标题）",
    size: "大小",
    path: "路径",
    transBadge: (lang: string) => `译→${lang}`,
    yes: "是",
    no: "否",
    unregisteredHint: "该文件未在登记处记录，仅提供打开操作",
  },
  settings: {
    title: "设置",
    secParse: "解析模型",
    secProviders: "大模型提供商",
    secOptions: "选项",
    mineruToken: "MinerU Token",
    mineruDesc: "云端高精度解析引擎",
    paddleocrToken: "PaddleOCR Token",
    paddleocrDesc: "百度 AI Studio 免费额度",
    advanced: "高级",
    paddleocrApiUrl: "PaddleOCR API 地址",
    providerModels: (n: number) => `${n} 个模型`,
    providerEnable: "启用该提供商",
    fillKeyFirst: "请先填写 API Key",
    signup: "申请密钥",
    backToProviders: "返回提供商列表",
    baseUrl: "Base URL",
    apiKey: "API Key",
    apiKeySaved: "已保存",
    apiKeyClear: "清除",
    apiKeyPlaceholder: "sk-…",
    testConnection: "测试连接",
    testing: "测试中…",
    modelList: "模型列表",
    addModel: "输入型号 id 后激活",
    add: "添加",
    fetchModels: "从 /models 拉取",
    fetching: "拉取中…",
    toastFetched: (n: number) => `已拉取，新增 ${n} 个型号`,
    toastFetchedNone: "拉取成功，没有新型号",
    visionYes: "视觉",
    visionNo: "仅文本",
    removeModel: "移除",
    toastTestFail: (msg: string) => `连接失败：${msg}`,
    groupDefaults: "默认选项",
    defaultMode: "默认解析模式",
    defaultLang: "默认翻译语言",
    defaultOutputDir: "默认输出目录",
    defaultWorkers: "默认并发 workers",
    defaultReasoning: "默认思考档",
    defaultVlmModel: "默认多模态模型",
    defaultPostModel: "默认后处理模型",
    visionOnlyHint: "只列已启用的视觉型号",
    postModelHint: "只列已启用型号（不限视觉）",
    noModel: "未配置（回退 .env）",
    browse: "浏览…",
    groupAppearance: "外观",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    zoomHint: (pct: number) => `Ctrl + / Ctrl − / Ctrl+滚轮缩放，Ctrl 0 复原（当前 ${pct}%）`,
    zoomReset: "重置 100%",
    groupSound: "完成提示音",
    soundLabel: "转换完成后播放提示音",
    soundPreview: "试听",
    groupAbout: "更新与关于",
    version: "版本",
    checkUpdate: "检查更新",
    checking: "检查中…",
    updateLatest: "当前已是最新版本",
    updateFound: (v: string) => `发现新版本：v${v}`,
    updateDownload: "下载地址",
    updateFailed: (e: string) => `检查更新失败：${e}`,
    license: "开源协议：见仓库 LICENSE",
  },
  manual: {
    title: "手册",
    secWhat: "这是什么",
    whatOneLiner:
      "Books Converter 把 PDF 书籍（含扫描件）转换为可重排版的电子书：EPUB / Markdown / TeX。",
    whatPipeline: ["PDF", "解析", "结构重建", "装订 / 导出"],
    whatStages: [
      "逐页识别文字、标题、图片、表格",
      "重建章节层级、跨页拼接、脚注目次",
      "产出 EPUB / Markdown / TeX（可选翻译）",
    ],
    secQuick: "快速开始",
    quick: [
      {
        t: "配置模型",
        d: "设置 → 大模型提供商：选一家多模态提供商（如智谱 GLM），填 API Key 并激活一个视觉型号（如 GLM-5.3-Flash），即可用 VLM 模式。或用规则模式：设置 → 解析模型填 MinerU / PaddleOCR Token，再选一个后处理模型。",
      },
      {
        t: "拖入 PDF",
        d: "回到转换页，把 PDF 拖进虚线框（可多本排队），选好输出目录与格式。",
      },
      {
        t: "开始转换",
        d: "点「开始转换」，实时进度与日志可见；完成后到产物库打开 EPUB。",
      },
    ],
    secModes: "两种模式怎么选",
    modeHead: ["", "规则", "VLM"],
    modeRows: [
      ["原理", "云端 OCR 解析版面，后处理模型重建章节结构", "多模态大模型逐页直读，同一模型完成转写与结构判断"],
      ["成本", "近零（只花后处理模型的文本 token）", "几元量级 / 400 页（视所选型号定价）"],
      ["速度", "较快", "较慢（逐页调用，可开并发）"],
      ["强项", "图片直截原图、表格解析成熟（MinerU），常规排版性价比高", "脚注重建、复杂结构判断明显更强"],
      ["局限", "脚注与复杂版面依赖 OCR 质量", "需视觉模型；老旧破损扫描件仍是天花板"],
    ],
    modesHint:
      "VLM 模式的模型能力直接决定转换质量：请选用 DeepSeek-V4.1-Flash、GLM-5.3-Flash 或更先进的型号，旧型号格式服从性不足，不要贪便宜。",
    secOptions: "选项说明",
    options: [
      ["强制 OCR", "扫描件与公式密集书籍必须开启——文字层直取时公式解析质量严重下降；仅纯文字版 PDF 可关闭提速。默认开启，仅规则模式有此开关。"],
      ["导出格式", "EPUB / Markdown / TeX 多选；Markdown 可选单文件或按章拆分（index.md + chapters/）、GFM 或 Pandoc 方言；TeX 可选完整文档或片段。"],
      ["翻译", "转换后由后处理模型翻译全书，可选目标语言；导出语言控制 EPUB/TeX 用原文、译文或双出。"],
      ["思考档", "VLM 模型的思考强度：off/low/medium/high。恒思考型号选 low 即最优；不支持的端点该选项自动隐藏。"],
      ["并发 workers", "VLM 逐页调用的并发数（1–8）。免费额度端点建议 ≤4。"],
    ],
    secFaq: "FAQ",
    faqs: [
      ["转换卡住了怎么办？", "展开该任务的日志看最后一行；超过 3 分钟无进展会出现停滞提示。先取消，再检查对应 Key 与网络，然后重新开始。"],
      ["产物在哪里？", "产物库页列出全部历史产物，可一键打开或在文件夹显示；文件本体在你选择的输出目录。"],
      ["提示音怎么关？", "设置 → 选项 → 完成提示音，关闭开关即可。"],
      ["扫描质量很差的老书能转吗？", "原件质量极差的扫描件（如很老的报纸），识别效果会受原件本身限制，属于正常现象；如有更清晰的版本，建议换用。"],
      ["书目敏感怎么办？", "可选用海外模型：设置 → 大模型提供商 → 自定义 OpenAI 兼容端点，填你自己的 Base URL 与 Key。"],
    ],
    openLink: "打开官网",
  },
  common: {
    cancel: "取消",
    confirm: "确认",
    close: "关闭",
  },
  empty: {
    queue: { title: "暂无转换任务", hint: "把 PDF 拖入上方虚线框，点「开始转换」开跑" },
    library: { title: "暂无产物", hint: "完成一次转换后，EPUB / Markdown / TeX 会出现在这里" },
    notifications: { title: "暂无通知", hint: "转换完成、失败与提醒都会汇聚到这里" },
  },
  err: {
    invalidKey: "密钥无效或未开通服务",
    rateLimited: "触发限流，稍后再试或降低并发",
    network: "网络连接失败，检查网络或代理",
    unknown: "未知错误",
  },
  precheck: {
    mineruToken: "MinerU Token",
    paddleocrToken: "PaddleOCR Token",
    postModelKey: (m: string) => `后处理模型 ${m} 的 API Key`,
    vlmModelKey: (m: string) => `多模态模型 ${m} 的 API Key`,
    vlmNoModel: "多模态模型（未选择）",
  },
  select: {
    emptyOptions: "无可选项",
  },
};

export function formatElapsed(s: number): string {
  if (s < 60) return `${Math.round(s)} 秒`;
  const m = Math.floor(s / 60);
  const sec = Math.round(s % 60);
  if (m < 60) return sec ? `${m} 分 ${sec} 秒` : `${m} 分钟`;
  const h = Math.floor(m / 60);
  return `${h} 小时 ${m % 60} 分`;
}
